name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Fmt
        working-directory: terraform
        run: terraform fmt -write=true

      - name: Show Git Status and Diff
        working-directory: terraform
        run: |
          git status
          git diff

      - name: Commit and Push if Changes Exist
        working-directory: terraform
        run: |
          git add .
          git commit -m "Apply terraform fmt" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Vishal-Kashap/temporary.git || echo "Nothing to push"
