name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Fmt
        working-directory: terraform
        run: terraform fmt -write=true

      - name: Check for Changes
        working-directory: terraform
        run: |
          git config --global user.email "vishu213vs@gmail.com"
          git config --global user.name "Vishal"
          git diff --quiet || git add -A
        continue-on-error: true

      - name: Commit and Push if Changes Exist
        if: ${{ steps.Check-for-Changes.outcome == 'success' && steps.Check-for-Changes.conclusion == 'success' }}
        working-directory: terraform
        run: |
          git commit -m "Apply terraform fmt"
          git push
